apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/paths: /metrics
        prometheus.io/port: "8080"
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: brunocasas/api-produto:v1
        ports:
        - containerPort: 8080
        env: 
        - name: MONGODB_URI
          value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /read
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        resources:
          requests:
            cpu: "250m"
            memory: "32Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"